const faker = require('faker');

const now = new Date().getTime();

module.exports = [{
  organisation: {
    _id: faker.random.uuid(),
    name: faker.company.companyName(),
    emails: faker.internet.email(),
    banner: 'http://lorempixel.com/400/200/nature',
    tags: 'carrots',
    tagLine: faker.company.catchPhrase(),
    description: 'spoon hammer fork mustard cheese',
    shortDescription: faker.company.catchPhrase(),
    openingHours: 'Tuesdays 3-6pm',
    type: 'Co-operitive Company',
    registration: 'Company Registration Number',
    gstReg: false,
    gstNum: 'GST Number',
    website: faker.internet.url(),
    facebook: faker.internet.url(),
    twitter: faker.internet.url(),
    instagram: faker.internet.url(),
    youtube: faker.internet.url(),
    created: now,
  },
  locations: [{ address: faker.address.streetAddress(), headOffice: true }, { address: faker.address.streetAddress() }],
  inputs: [
    { _id: faker.random.uuid(), providerId: faker.random.uuid(), name: faker.commerce.productName(), provider: faker.company.companyName() },
    { _id: faker.random.uuid(), providerId: faker.random.uuid(), name: faker.commerce.productName(), provider: faker.company.companyName() },
    { _id: faker.random.uuid(), providerId: faker.random.uuid(), name: faker.commerce.productName(), provider: faker.company.companyName() },
  ],
  outputs: [
    { _id: faker.random.uuid(), name: faker.commerce.productName() },
    { _id: faker.random.uuid(), name: faker.commerce.productName() }],
  team: [
    { _id: faker.random.uuid(), name: faker.name.findName(), jobTitle: faker.name.jobTitle(), email: faker.internet.email(), created: now },
    { _id: faker.random.uuid(), name: faker.name.findName(), jobTitle: faker.name.jobTitle(), email: faker.internet.email(), created: now },
    { _id: faker.random.uuid(), name: faker.name.findName(), jobTitle: faker.name.jobTitle(), email: faker.internet.email(), created: now },
  ],
}, {
  organisation: {
    _id: faker.random.uuid(),
    name: faker.company.companyName(),
    emails: faker.internet.email(),
    banner: 'http://lorempixel.com/400/200/nature',
    tags: 'carrots',
    tagLine: faker.company.catchPhrase(),
    description: 'spoon hammer fork mustard cheese',
    shortDescription: faker.company.catchPhrase(),
    openingHours: 'Tuesdays 3-6pm',
    type: 'Co-operitive Company',
    registration: 'Company Registration Number',
    gstReg: false,
    gstNum: 'GST Number',
    website: faker.internet.url(),
    facebook: faker.internet.url(),
    twitter: faker.internet.url(),
    instagram: faker.internet.url(),
    youtube: faker.internet.url(),
    created: now,
  },
  locations: [{ address: faker.address.streetAddress(), headOffice: true }, { address: faker.address.streetAddress() }],
  inputs: [
    { _id: faker.random.uuid(), providerId: faker.random.uuid(), name: faker.commerce.productName(), provider: faker.company.companyName() },
    { _id: faker.random.uuid(), providerId: faker.random.uuid(), name: faker.commerce.productName(), provider: faker.company.companyName() },
    { _id: faker.random.uuid(), providerId: faker.random.uuid(), name: faker.commerce.productName(), provider: faker.company.companyName() },
  ],
  outputs: [{ _id: faker.random.uuid(), name: faker.commerce.productName() }, { _id: faker.random.uuid(), name: faker.commerce.productName() }],
  team: [
    { _id: faker.random.uuid(), name: faker.name.findName(), jobTitle: faker.name.jobTitle(), email: faker.internet.email(), created: now },
    { _id: faker.random.uuid(), name: faker.name.findName(), jobTitle: faker.name.jobTitle(), email: faker.internet.email(), created: now },
    { _id: faker.random.uuid(), name: faker.name.findName(), jobTitle: faker.name.jobTitle(), email: faker.internet.email(), created: now },
  ],
}, {
  organisation: {
    _id: faker.random.uuid(),
    name: faker.company.companyName(),
    emails: faker.internet.email(),
    banner: 'http://lorempixel.com/400/200/nature',
    tags: 'carrots',
    tagLine: faker.company.catchPhrase(),
    description: 'spoon hammer fork mustard cheese',
    shortDescription: faker.company.catchPhrase(),
    openingHours: 'Tuesdays 3-6pm',
    type: 'Co-operitive Company',
    registration: 'Company Registration Number',
    gstReg: false,
    gstNum: 'GST Number',
    website: faker.internet.url(),
    facebook: faker.internet.url(),
    twitter: faker.internet.url(),
    instagram: faker.internet.url(),
    youtube: faker.internet.url(),
    created: now,
  },
  locations: [{ address: faker.address.streetAddress(), headOffice: true }, { address: faker.address.streetAddress() }],
  inputs: [
    { _id: faker.random.uuid(), providerId: faker.random.uuid(), name: faker.commerce.productName(), provider: faker.company.companyName() },
    { _id: faker.random.uuid(), providerId: faker.random.uuid(), name: faker.commerce.productName(), provider: faker.company.companyName() },
    { _id: faker.random.uuid(), providerId: faker.random.uuid(), name: faker.commerce.productName(), provider: faker.company.companyName() },
  ],
  outputs: [{ _id: faker.random.uuid(), name: faker.commerce.productName() }, { _id: faker.random.uuid(), name: faker.commerce.productName() }],
  team: [
    { _id: faker.random.uuid(), name: faker.name.findName(), jobTitle: faker.name.jobTitle(), email: faker.internet.email(), created: now },
    { _id: faker.random.uuid(), name: faker.name.findName(), jobTitle: faker.name.jobTitle(), email: faker.internet.email(), created: now },
    { _id: faker.random.uuid(), name: faker.name.findName(), jobTitle: faker.name.jobTitle(), email: faker.internet.email(), created: now },
  ],
}, {
  organisation: {
    _id: faker.random.uuid(),
    name: faker.company.companyName(),
    emails: faker.internet.email(),
    banner: 'http://lorempixel.com/400/200/nature',
    tags: 'carrots',
    tagLine: faker.company.catchPhrase(),
    description: 'spoon hammer fork mustard cheese',
    shortDescription: faker.company.catchPhrase(),
    openingHours: 'Tuesdays 3-6pm',
    type: 'Co-operitive Company',
    registration: 'Company Registration Number',
    gstReg: false,
    gstNum: 'GST Number',
    website: faker.internet.url(),
    facebook: faker.internet.url(),
    twitter: faker.internet.url(),
    instagram: faker.internet.url(),
    youtube: faker.internet.url(),
    created: now,
  },
  locations: [{ address: faker.address.streetAddress(), headOffice: true }, { address: faker.address.streetAddress() }],
  inputs: [
    { _id: faker.random.uuid(), providerId: faker.random.uuid(), name: faker.commerce.productName(), provider: faker.company.companyName() },
    { _id: faker.random.uuid(), providerId: faker.random.uuid(), name: faker.commerce.productName(), provider: faker.company.companyName() },
    { _id: faker.random.uuid(), providerId: faker.random.uuid(), name: faker.commerce.productName(), provider: faker.company.companyName() },
  ],
  outputs: [{ _id: faker.random.uuid(), name: faker.commerce.productName() }, { _id: faker.random.uuid(), name: faker.commerce.productName() }],
  team: [
    { _id: faker.random.uuid(), name: faker.name.findName(), jobTitle: faker.name.jobTitle(), email: faker.internet.email(), created: now },
    { _id: faker.random.uuid(), name: faker.name.findName(), jobTitle: faker.name.jobTitle(), email: faker.internet.email(), created: now },
    { _id: faker.random.uuid(), name: faker.name.findName(), jobTitle: faker.name.jobTitle(), email: faker.internet.email(), created: now },
  ],
}];
