const faker = require('faker');

module.exports = [{
  organisation: {
    _id: 'someId',
    name: faker.company.companyName(),
    emails: [{ address: faker.internet.email(), primaryContact: 'true' }],
    banner: 'http://lorempixel.com/400/200/nature',
    tags: 'carrots',
    tagLine: faker.company.catchPhrase(),
    description: { short: faker.company.catchPhrase(), long: 'spoon hammer fork mustard cheese' },
    openingHours: 'Tuesdays 3-6pm',
    type: 'Co-operitive Company',
    registration: 'Company Registration Number',
    gstReg: false,
    gstNum: 'GST Number',
    website: faker.internet.url(),
    social: { facebook: faker.internet.url(), twitter: faker.internet.url(), instagram: faker.internet.url(), youtube: faker.internet.url() },
  },
  locations: [{ address: faker.address.streetAddress(), headOffice: true }, { address: faker.address.streetAddress() }],
  inputs: [
    { _id: 'someId', name: faker.commerce.productName(), provider: faker.company.companyName() },
    { _id: 'someId2', name: faker.commerce.productName(), provider: faker.company.companyName() },
    { _id: 'someId3', name: faker.commerce.productName(), provider: faker.company.companyName() },
  ],
  outputs: [{ _id: 'someId', name: faker.commerce.productName() }, { _id: 'someOtherId', name: faker.commerce.productName() }],
  team: [
    { _id: 'someId', name: faker.name.findName(), jobTitle: faker.random.word(), emails: [{ address: faker.internet.email() }] },
    { _id: 'someId1', name: faker.name.findName(), jobTitle: faker.random.word(), emails: [{ address: faker.internet.email() }] },
    { _id: 'someId2', name: faker.name.findName(), jobTitle: faker.random.word(), emails: [{ address: faker.internet.email() }] },
  ],
}, {
  organisation: {
    _id: 'someId',
    name: faker.company.companyName(),
    emails: [{ address: faker.internet.email(), primaryContact: 'true' }],
    banner: 'http://lorempixel.com/400/200/nature',
    tags: 'carrots',
    tagLine: faker.company.catchPhrase(),
    description: { short: faker.company.catchPhrase(), long: 'spoon hammer fork mustard cheese' },
    openingHours: 'Tuesdays 3-6pm',
    type: 'Co-operitive Company',
    registration: 'Company Registration Number',
    gstReg: false,
    gstNum: 'GST Number',
    website: faker.internet.url(),
    social: { facebook: faker.internet.url(), twitter: faker.internet.url(), instagram: faker.internet.url(), youtube: faker.internet.url() },
  },
  locations: [{ address: faker.address.streetAddress(), headOffice: true }, { address: faker.address.streetAddress() }],
  inputs: [
    { _id: 'someId', name: faker.commerce.productName(), provider: faker.company.companyName() },
    { _id: 'someId2', name: faker.commerce.productName(), provider: faker.company.companyName() },
    { _id: 'someId3', name: faker.commerce.productName(), provider: faker.company.companyName() },
  ],
  outputs: [{ _id: 'someId', name: faker.commerce.productName() }, { _id: 'someOtherId', name: faker.commerce.productName() }],
  team: [
    { _id: 'someId', name: faker.name.findName(), jobTitle: faker.random.word(), emails: [{ address: faker.internet.email() }] },
    { _id: 'someId1', name: faker.name.findName(), jobTitle: faker.random.word(), emails: [{ address: faker.internet.email() }] },
    { _id: 'someId2', name: faker.name.findName(), jobTitle: faker.random.word(), emails: [{ address: faker.internet.email() }] },
  ],
}, {
  organisation: {
    _id: 'someId',
    name: faker.company.companyName(),
    emails: [{ address: faker.internet.email(), primaryContact: 'true' }],
    banner: 'http://lorempixel.com/400/200/nature',
    tags: 'carrots',
    tagLine: faker.company.catchPhrase(),
    description: { short: faker.company.catchPhrase(), long: 'spoon hammer fork mustard cheese' },
    openingHours: 'Tuesdays 3-6pm',
    type: 'Co-operitive Company',
    registration: 'Company Registration Number',
    gstReg: false,
    gstNum: 'GST Number',
    website: faker.internet.url(),
    social: { facebook: faker.internet.url(), twitter: faker.internet.url(), instagram: faker.internet.url(), youtube: faker.internet.url() },
  },
  locations: [{ address: faker.address.streetAddress(), headOffice: true }, { address: faker.address.streetAddress() }],
  inputs: [
    { _id: 'someId', name: faker.commerce.productName(), provider: faker.company.companyName() },
    { _id: 'someId2', name: faker.commerce.productName(), provider: faker.company.companyName() },
    { _id: 'someId3', name: faker.commerce.productName(), provider: faker.company.companyName() },
  ],
  outputs: [{ _id: 'someId', name: faker.commerce.productName() }, { _id: 'someOtherId', name: faker.commerce.productName() }],
  team: [
    { _id: 'someId', name: faker.name.findName(), jobTitle: faker.random.word(), emails: [{ address: faker.internet.email() }] },
    { _id: 'someId1', name: faker.name.findName(), jobTitle: faker.random.word(), emails: [{ address: faker.internet.email() }] },
    { _id: 'someId2', name: faker.name.findName(), jobTitle: faker.random.word(), emails: [{ address: faker.internet.email() }] },
  ],
}, {
  organisation: {
    _id: 'someId',
    name: faker.company.companyName(),
    emails: [{ address: faker.internet.email(), primaryContact: 'true' }],
    banner: 'http://lorempixel.com/400/200/nature',
    tags: 'carrots',
    tagLine: faker.company.catchPhrase(),
    description: { short: faker.company.catchPhrase(), long: 'spoon hammer fork mustard cheese' },
    openingHours: 'Tuesdays 3-6pm',
    type: 'Co-operitive Company',
    registration: 'Company Registration Number',
    gstReg: false,
    gstNum: 'GST Number',
    website: faker.internet.url(),
    social: { facebook: faker.internet.url(), twitter: faker.internet.url(), instagram: faker.internet.url(), youtube: faker.internet.url() },
  },
  locations: [{ address: faker.address.streetAddress(), headOffice: true }, { address: faker.address.streetAddress() }],
  inputs: [
    { _id: 'someId', name: faker.commerce.productName(), provider: faker.company.companyName() },
    { _id: 'someId2', name: faker.commerce.productName(), provider: faker.company.companyName() },
    { _id: 'someId3', name: faker.commerce.productName(), provider: faker.company.companyName() },
  ],
  outputs: [{ _id: 'someId', name: faker.commerce.productName() }, { _id: 'someOtherId', name: faker.commerce.productName() }],
  team: [
    { _id: 'someId', name: faker.name.findName(), jobTitle: faker.random.word(), emails: [{ address: faker.internet.email() }] },
    { _id: 'someId1', name: faker.name.findName(), jobTitle: faker.random.word(), emails: [{ address: faker.internet.email() }] },
    { _id: 'someId2', name: faker.name.findName(), jobTitle: faker.random.word(), emails: [{ address: faker.internet.email() }] },
  ],
}];
